version: '3'
services:
  hkpost-proxy:
    image: 'mmhk/hkpost-correct-addr-proxy'
    container_name: hkpost-correct-addr-proxy
    ports:
      - 3004:3000
    restart: always
    environment:
      PORT: ${PORT}
      API_ENDPOINT: ${API_ENDPOINT}
      AUTH_TOKEN: ${AUTH_TOKEN}
    #  限制 log file 大小
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
